apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: guestbook-dev
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 8765
      nodePort: 30333
  selector:
    run: gateway-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guestbook-dev
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway-service
  template:
    metadata:
      labels:
        run: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: 192.168.101.69:30080/guestbook/gateway-service:latest
        ports:
        - containerPort: 8765
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local