apiVersion: v1
kind: Service
metadata:
  namespace: guestbook-dev
  name: zipkin-service
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 9411
    nodePort: 30411
  selector:
    run: zipkin-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guestbook-dev
  name: zipkin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zipkin-service
  template:
    metadata:
      labels:
        run: zipkin-service
    spec:
      containers:
      - name: zipkin-service
        image: goharbor.com/demo/zipkin-service:latest
        env:
          - name: ZIPKIN_SERVER
            value: "zipkin-service"
          - name: ZIPKIN_SERVER_PORT
            value: "9411"
        ports:
        - containerPort: 9411
          protocol: TCP
      imagePullSecrets:
      - name: guestbook-harbor
#TODO have issue in K8S