apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: guestbook-dev
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 8761
      nodePort: 31002
  selector:
    run: discovery-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: guestbook-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: discovery-service
  template:
    metadata:
      labels:
        run: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: 192.168.101.69:30080/guestbook/discovery-service:latest
        ports:
        - containerPort: 8761
          protocol: TCP
      imagePullSecrets:
      - name: guestbook-harbor

